name: Fake composite workflow

on:
  workflow_call:
     inputs:
       ref:
         description: "Dummy"
         default: "foobar"
         type: string
       trigger-event:
         default: "hahaha"
         type: string

jobs:
  print_env:
    runs-on: ubuntu-latest
    env:
      EVENT_REF: ${{ github.event.ref }}
      EVENT_NAME: ${{ github.event_name }}
    steps:
      - run: echo ${{ github.event.ref }}
      - run: echo ${{ inputs.trigger-event }}
