Ha ha ha 
name: Print Hello
on:
  pull_request:
  push:
    branches:
      - main
      - foobar
      - hauptzweig
    tags:
      - f*

jobs:
  print_hello:
    name: "Print Hello"
    runs-on: ubuntu-latest
    env:
      REF_TYPE: ${{ github.ref_type }}
      DUMMY: ${{ secrets.DUMMY_SECRET }}
      MERGEBOT_TOKEN: ${{ secrets.MERGEBOT_TOKEN }}
      LIMIT: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha}}
    steps:
      - name: Print Hello
        run: |
          echo "Hello World"
          echo ${DUMMY}|md5sum -
          echo ${MERGEBOT_TOKEN}|md5sum -          

      - name: Print on Push to foobar
        if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/foobar' }}
        run: echo "Hello on push ${{ github.event.ref }}"        
  oidc_debug_test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    name: A test of the oidc debugger
    steps:
      - name: Checkout actions-oidc-debugger
        uses: actions/checkout@v3
        with:
          repository: github/actions-oidc-debugger
          ref: main
          path: ./.github/actions/actions-oidc-debugger
      - name: Debug OIDC Claims
        uses: ./.github/actions/actions-oidc-debugger
        with:
          audience: '${{ github.server_url }}/${{ github.repository_owner }}'
