name: Install torch on macos-latest

on:
  pull_request:
      paths:
      - .github/workflows/install_torch.yml
  push:
    branches:
      - hauptzweig
    paths:
      - .github/workflows/install_torch.yml
  workflow_dispatch:

jobs:
  install_torch:
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest", "macos-15"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Python-3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.14.0t"
          allow-prereleases: true
      - name: Print Python version
        shell: bash {0}
        run:  python --version
      - name: Print Python3 version
        shell: bash -l {0}
        run:  python3 --version
      - name: Print Environment
        shell: bash -l {0}
        run:  env
      - name: Install PyTorch and Numpy
        shell: bash {0}
        run:  pip install torch numpy
      - name: Run Python script
        shell: python {0}
        run: |
          import sys
          import torch
          print(f"Python version is {sys.version} torch version is {torch.__version__}")
          x = torch.rand(3, 3, dtype=torch.float16)
          print(x.sum())
